[phases.setup]
nixPkgs = ["python310", "postgresql_16.dev", "gcc"]

[phases.install]
cmd = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[phases.build]
cmd = "pip install -r requirements.txt"

[start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false --browser.gatherUsageStats=false"
